---
- name: Import Automation Controller Configs
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Assert defined variables
      ansible.builtin.assert:
        that:
          - aap_hostname is defined
          - aap_username is defined
          - aap_password is defined
        fail_msg: "You must define aap_hostname, aap_username, and aap_password in vars.yml."
  roles:
    - {role: infra.controller_configuration.credential_types, when: controller_credential_types is defined}
    - {role: infra.controller_configuration.settings, when: controller_settings is defined}
    - {role: infra.controller_configuration.organizations, when: controller_organizations is defined}
    - {role: infra.controller_configuration.credentials, when: import_creds and controller_credentials is defined}
    - {role: infra.controller_configuration.projects, when: controller_projects is defined}
    - {role: infra.controller_configuration.execution_environments, when: controller_execution_environments is defined, ignore_errors: true}
    - {role: infra.controller_configuration.inventories, when: controller_inventories is defined}
    - {role: infra.controller_configuration.inventory_sources, when: controller_inventory_sources is defined}
    - {role: infra.controller_configuration.hosts, when: controller_hosts is defined}
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}

...
